language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-evolve' ]; then cd .. && eval "mv $currentfolder generator-evolve" && cd generator-evolve; fi
